config/routes.rb
class QueryStringConstraint
  def initialize(key)
    @key = key
  end

  def matches?(req)
    req.params.has_key?(@key)
  end
end

Rails.application.routes.draw do
  get 'welcome/index'

  resources :manifests, param: :uuid, only: %i[show new create destroy]

  # Redirect /?uuid=<uuid> to /manifests/<uuid>.js
  constraints(QueryStringConstraint.new(:uuid)) do
    root to: redirect { |_, req| "/manifests/#{req.params[:uuid]}.sh" }
  end

  root "welcome#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/manifest.rb
class Manifest < ApplicationRecord
  # TODO: store those in postgres instead of exporting everything into `content`
  FIELDS = [:app, :platform, :compute, :dns, :cloud].freeze

  attr_accessor(*FIELDS)

  before_save do
    self.uuid ||= SecureRandom.uuid

    # transform csv into ruby array
    if app.is_a?(Hash) && app[:domains].is_a?(String)
      app[:domains] = app[:domains].split(/[, ]+/)
    end

    fill_blank_attributes

    # export attributes to database (in JSON format)
    FIELDS.each do |field|
      value = send(field)
      content[field] = value unless value.nil?
    end
  end

  def fill_blank_attributes
    if cloud.present? # landing page
      self.compute = {
        provider: cloud[:provider]
      }
      self.dns = {
        provider: cloud[:provider]
      }
      
      case cloud[:provider]
      when "digitalocean"
        compute[:region] = "sfo1"
        compute[:image] = "ubuntu-16-04-x64"
        case platform[:provider]
        when "dokku"
          compute[:size] = "1gb"
          compute[:count] = "1"
        when "flynn"
          compute[:size] = "4gb"
          compute[:count] = "3"
        end
      when "aws"
        compute[:region] = "us-west-2"
        compute[:image_id] = "ami-6e1a0117"
        case platform[:provider]
        when "dokku"
          compute[:flavor_id] = "t2.micro"
          compute[:count] = "1"
        when "flynn"
          compute[:flavor_id] = "t2.medium"
          compute[:count] = "3"
        end
      end

      self.cloud = nil
    end

    case platform[:provider]
    when "dokku"
      platform[:version] = "v0.10.4"
    end
    
    platform[:domain] ||= app[:domains].first || "example.com" # error if empty?
    app[:name] ||= platform[:domain].tr(".", "-")
  end

  def providers
    {}.tap do |hash|
      %w[platform compute dns].each do |field|
        provider = content[field]["provider"]
        hash[provider] = true
      end
    end
  end

  def to_param
    uuid
  end
end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html

  protect_from_forgery with: :exception
end

app/controllers/manifests_controller.rb
class ManifestsController < ApplicationController
  respond_to :html
  respond_to :json, only: :show
  respond_to :sh, only: :show

  expose :manifests, ->{ Manifest.all }
  expose! :manifest, find_by: :uuid, id: ->{ params[:uuid] }

  def create
    manifest.save
    respond_with(manifest)
  end

  def destroy
    manifest.destroy
    respond_with(manifest, location: root_path)
  end

  private

  def manifest_params
    params.require(:manifest).permit(
      ssh: [:key],
      app: [:name, :domains, services: []],
      platform: [:provider, :domain, :version],
      compute: [:provider, :region, :image, :image_id, :flavor_id, :size, :count],
      dns: [:provider],
      cloud: [:provider]
    )
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  expose :manifest

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for(flash_type)
    hash = {
      alert: "alert-danger",
      notice: "alert-success"
    }

    hash.fetch(flash_type.to_sym, flash_type)
  end
end

app/views/home/index.html.erb
<h1 class="display-3 my-5 text-center">Provisioning.sh</h1>

<form id="provisioning" v-on:submit.prevent>
  <div class="card">
    <div class="card-header">
      <ul id="provisioning-tabs" class="nav nav-tabs card-header-tabs" role="tablist">
        <li class="nav-item">
        </li>
        <li class="nav-item">
          <a id="app-tab" class="nav-link active" href="#app" data-toggle="tab" role="tab">App</a>
        </li>
        <li class="nav-item">
          <a id="platform-tab" class="nav-link" href="#platform" data-toggle="tab" role="tab">Platform</a>
        </li>
        <li class="nav-item">
          <a id="hosting-tab" class="nav-link" href="#hosting" data-toggle="tab" role="tab">Hosting</a>
        </li>
        <li class="nav-item">
          <a id="dns-tab" class="nav-link" href="#dns" data-toggle="tab" role="tab">DNS</a>
        </li>
        <li class="nav-item">
          <a id="save-tab" class="nav-link" href="#save" data-toggle="tab" role="tab">Save</a>
        </li>
      </ul>
    </div>

    <div class="card-body tab-content">
      <div class="tab-pane fade show active" id="app" role="tabpanel" aria-labelledby="app-tab">
        <h4 class="card-title">App settings</h4>

        <div class="form-group">
          <label for="app-name">Name</label>
          <input type="text" class="form-control" id="app-name" aria-describedby="app-name-help" placeholder="app" v-model="app">
          <p id="app-name-help" class="form-text text-muted">https://<strong>{{helps.app}}</strong>.{{helps.domain}}</p>
        </div>

        <div class="form-group">
          <label for="app-domains">Custom domains</label>
          <input type="text" class="form-control" id="app-domains" placeholder="app.com, www.app.com">
        </div>

        <div class="form-group">
          <label for="app-services">Services</label>
          <select class="form-control" id="app-services" multiple>
            <option>Mongo</option>
            <option>Postgres</option>
            <option>Redis</option>
          </select>
        </div>
      </div>

      <div class="tab-pane fade" id="platform" role="tabpanel" aria-labelledby="platform-tab">
        <h4 class="card-title">Platform settings</h4>

        <div class="form-group">
          <label for="platform">Platform</label>
          <select class="form-control" id="platform" v-model="providers.platform">
            <option value="dokku">Dokku</option>
            <option value="flynn">Flynn</option>
          </select>
        </div>

        <div v-if="providers.platform === 'dokku'">
          <div class="form-group">
            <label for="dokku-version">Version</label>
            <select class="form-control" id="dokku-version">
              <option>v0.10.4</option>
              <option>v0.9.4</option>
              <option>v0.8.2</option>
            </select>
          </div>
        </div>

        <div class="form-group">
          <label for="ssh-key-fingerprint">SSH key fingerprint</label>
          <input type="text" class="form-control" id="ssh-key-fingerprint" placeholder="01:23:45:67:89:AB:CD:EF:01:23:45:67:89:AB:CD:EF">
        </div>
      </div>

      <div class="tab-pane fade" id="hosting" role="tabpanel" aria-labelledby="hosting-tab">
        <h4 class="card-title">Hosting settings</h4>

        <div class="form-group">
          <label for="hosting">Hosting</label>
          <select class="form-control" id="hosting" v-model="providers.hosting">
            <option value="digitalocean">DigitalOcean</option>
            <option value="linode">Linode</option>
            <option value="rackspace">Rackspace</option>
          </select>
        </div>

        <div v-if="providers.hosting === 'digitalocean'">
          <div class="form-group">
            <label for="digitalocean-api-token">API token</label>
            <input type="text" class="form-control" id="digitalocean-api-token" placeholder="0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef">
          </div>

          <div class="form-group">
            <label for="digitalocean-server-image">Server image</label>
            <select class="form-control" id="digitalocean-server-image">
              <option>Ubuntu 16.04.3 x64</option>
              <option>Ubuntu 16.04.3 x32</option>
              <option>Ubuntu 14.04.5 x64</option>
              <option>Ubuntu 14.04.5 x32</option>
            </select>
          </div>

          <div class="form-group">
            <label for="digitalocean-server-size">Server size</label>
            <select class="form-control" id="digitalocean-server-size">
              <option>1 CPU / 512 MB</option>
              <option>1 CPU / 1 GB</option>
              <option>2 CPU / 2 GB</option>
              <option>2 CPU / 4 GB</option>
              <option>4 CPU / 8 GB</option>
            </select>
          </div>

          <div class="form-group">
            <label for="digitalocean-server-region">Server region</label>
            <select class="form-control" id="digitalocean-server-region">
              <option>Amsterdam 2</option>
              <option>Amsterdam 3</option>
              <option>Frankfurt 1</option>
              <option>London 1</option>
              <option>New York 1</option>
              <option>New York 3</option>
              <option>San Francisco 1</option>
              <option>San Francisco 2</option>
            </select>
          </div>
        </div>
      </div>

      <div class="tab-pane fade" id="dns" role="tabpanel" aria-labelledby="dns-tab">
        <h4 class="card-title">DNS settings</h4>

        <div class="form-group">
          <label for="dns">DNS</label>
          <select class="form-control" id="dns" v-model="providers.dns">
            <option value="digitalocean">DigitalOcean</option>
            <option value="linode">Linode</option>
            <option value="rackspace">Rackspace</option>
          </select>
        </div>

        <div class="form-group">
          <label for="domain">Wildcard domain</label>
          <input type="text" class="form-control" id="domain" aria-describedby="domain-help" placeholder="example.com" v-model="domain">
          <p id="domain-help" class="form-text text-muted">https://{{helps.app}}.<strong>{{helps.domain}}</strong></p>
        </div>
      </div>

      <div class="tab-pane fade" id="save" role="tabpanel" aria-labelledby="save-tab">
        <h4 class="card-title">Save settings</h4>

        <div class="lead text-secondary bg-light p-3 my-4 border rounded">
          <samp>$ curl "https://provisioning.sh?uuid=<%= SecureRandom.uuid %>" | sh</samp>
        </div>

        <div class="text-center">
          <button type="submit" class="btn btn-lg btn-primary">Save</button>
        </div>
      </div>
    </div>
  </div>
</form>

app/views/layouts/_alerts.html.erb
<% flash.each do |type, message| %>
  <div class="alert <%= bootstrap_class_for(type) %> alert-dismissible fade show" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>

    <%= message %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Provisioning.sh</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>
    <%= javascript_pack_tag "provisioning" %>
  </head>

  <body class="<%= controller.controller_name %>">
    <div class="container d-flex flex-column" style="min-height:100vh">
      <section>
        <%= render "layouts/alerts" %>

        <%= yield %>
      </section>

      <footer class="mt-auto credits">
        <p class="text-center mt-5">
          <span>Built with &hearts; by <a href="https://vinc.cc"><strong>vinc</strong></a>.</span>
          <span>Code licensed <a href="https://github.com/vinc/provisioning.sh/blob/master/LICENSE"><strong>MIT</strong></a>.</span>
        </p>
      </footer>
    </div>
  </body>
</html>

app/views/manifests/_console_aws_provisioning.html.erb
$ export AWS_ACCESS_KEY_ID=xxxxxxx
$ export AWS_SECRET_ACCESS_KEY=xxxxxxx
$ curl -sSL "<%= root_url(uuid: manifest.uuid).sub("/?uuid", "?uuid") %>" | bash

app/views/manifests/_console_digitalocean_provisioning.html.erb
$ export DIGITALOCEAN_TOKEN=xxxxxxx
$ curl -sSL "<%= root_url(uuid: manifest.uuid).sub("/?uuid", "?uuid") %>" | bash

app/views/manifests/_console_manual_provisioning.html.erb
$ gem install provisioning
$ curl -o manifest.json "<%= manifest_url(format: :json) %>"
$ export SSH_PUBLIC_KEY="$(cat ~/.ssh/id_rsa.pub)"
$ provision manifest.json

app/views/manifests/new.html.erb
<div class="content p-4 rounded">
  <h1 class="display-4 text-center">Provisioning manifest</h1>

  <hr>

  <%= form_with model: manifest, local: true, id: "provisioning" do |form| %>
    <h3 class="text-center">App</h3>

    <div class="form-group">
      <label for="app-name">Name</label>
      <input id="app-name" name="manifest[app][name]" type="text" class="form-control" aria-describedby="app-name-help" placeholder="app" v-model="app">
      <p id="app-name-help" class="form-text text-muted" v-cloak>https://<strong>{{helps.app}}</strong>.{{helps.domain}}</p>
    </div>

    <div class="form-group">
      <label for="app-domains">Custom domains</label>
      <input id="app-domains" name="manifest[app][domains]" type="text" class="form-control" placeholder="app.com, www.app.com">
    </div>

    <div class="form-group">
      <label for="app-services">Services</label>
      <select id="app-services" name="manifest[app][services][]" class="form-control" multiple>
        <option value="mongo">Mongo</option>
        <option value="mysql">MySQL</option>
        <option value="postgres">Postgres</option>
        <option value="redis">Redis</option>
      </select>
    </div>

    <hr>

    <h3 class="text-center">Platform</h3>

    <div class="form-group">
      <label for="platform">Platform provider</label>
      <select id="platform" name="manifest[platform][provider]" class="form-control" v-model="providers.platform">
        <option value="dokku">Dokku</option>
        <option value="flynn">Flynn</option>
      </select>
    </div>

    <div class="form-group">
      <label for="domain">Platform domain</label>
      <input id="domain" name="manifest[platform][domain]" type="text" class="form-control" aria-describedby="domain-help" placeholder="example.com" required v-model="domain">
      <p id="domain-help" class="form-text text-muted" v-cloak>https://{{helps.app}}.<strong>{{helps.domain}}</strong></p>
    </div>

    <hr>

    <h3 class="text-center">Compute</h3>

    <div class="form-group">
      <label for="compute">Compute provider</label>
      <select id="compute" name="manifest[compute][provider]" class="form-control" v-model="providers.compute">
        <option value="aws">Amazon EC2</option>
        <option value="digitalocean" selected>DigitalOcean</option>
        <option value="linode">Linode</option>
        <option value="rackspace">Rackspace</option>
      </select>
    </div>

    <div v-if="providers.compute === 'aws'">
      <div class="form-group">
        <label for="aws-region">AWS region</label>
        <select id="aws-region" name="manifest[compute][region]" class="form-control">
          <option value="us-west-2">Oregon</option>
        </select>
      </div>

      <div class="form-group">
        <label for="aws-image">Server image</label>
        <select id="aws-image" name="manifest[compute][image_id]" class="form-control">
          <option value="ami-6e1a0117" selected>Ubuntu 16.04 LTS</option>
        </select>
      </div>

      <div class="form-group">
        <label for="aws-size">Server size</label>
        <select id="aws-size" name="manifest[compute][flavor_id]" class="form-control">
          <option value="t2.nano">1 CPU / 0.5 GB</option>
          <option value="t2.micro" selected>1 CPU / 1 GB</option>
          <option value="t2.small">1 CPU / 2 GB</option>
          <option value="t2.medium">2 CPU / 4 GB</option>
          <option value="t2.large">2 CPU / 8 GB</option>
          <option value="t2.xlarge">4 CPU / 16 GB</option>
          <option value="t2.2xlarge">8 CPU / 32 GB</option>
        </select>
      </div>
    </div>

    <div v-if="providers.compute === 'digitalocean'">
      <div class="form-group">
        <label for="digitalocean-region">Server region</label>
        <select id="digitalocean-region" name="manifest[compute][region]" class="form-control">
          <option value="ams2">Amsterdam 2</option>
          <option value="ams3">Amsterdam 3</option>
          <option value="fra1">Frankfurt 1</option>
          <option value="lon1">London 1</option>
          <option value="nyc1" selected>New York 1</option>
          <option value="nyc3">New York 3</option>
          <option value="sfo1">San Francisco 1</option>
          <option value="sfo2">San Francisco 2</option>
          <option value="sgp1">Singapore 1</option>
        </select>
      </div>

      <div class="form-group">
        <label for="digitalocean-image">Server image</label>
        <select id="digitalocean-image" name="manifest[compute][image]" class="form-control">
          <option value="ubuntu-17-04-x64">Ubuntu 17.04</option>
          <option value="ubuntu-16-04-x64" selected>Ubuntu 16.04 LTS</option>
          <option value="ubuntu-14-04-x64">Ubuntu 14.04 LTS</option>
        </select>
      </div>

      <div class="form-group">
        <label for="digitalocean-size">Server size</label>
        <select id="digitalocean-size" name="manifest[compute][size]" class="form-control">
          <option value="512mb">1 CPU / 512 MB</option>
          <option value="1gb" selected>1 CPU / 1 GB</option>
          <option value="2gb">2 CPU / 2 GB</option>
          <option value="4gb">2 CPU / 4 GB</option>
          <option value="8gb">4 CPU / 8 GB</option>
        </select>
      </div>
    </div>

    <div class="form-group">
      <label for="compute-count">Cluster size</label>
      <input id="app-name" name="manifest[compute][count]" type="number" class="form-control" placeholder="1" value="1">
    </div>

    <hr>

    <h3 class="text-center">DNS</h3>

    <div class="form-group">
      <label for="dns">DNS provider</label>
      <select id="dns" name="manifest[dns][provider]" class="form-control" v-model="providers.dns">
        <option value="aws">Amazon Route 53</option>
        <option value="digitalocean" selected>DigitalOcean</option>
        <option value="linode">Linode</option>
        <option value="rackspace">Rackspace</option>
      </select>
    </div>

    <hr>

    <div class="text-center mt-5 mb-4">
      <button type="submit" class="btn btn-lg btn-success" style="background:chartreuse">Generate</button>
    </div>
  <% end %>
</div>

app/views/manifests/show.html.erb
<div class="content p-4 rounded">
  <h1 class="display-4 text-center">Provisioning manifest</h1>

  <hr class="my-4">

  <% if manifest.providers["aws"] %>
    <p>
      Export your <a href="http://docs.aws.amazon.com/general/latest/gr/managing-aws-access-keys.html">AWS access key</a>
      and run this provisioning script to create your platform:
    </p>

    <pre class="p-3 my-4 text-console bg-console border border-console rounded"><code><%= render "console_aws_provisioning" %></code></pre>
  <% else %>
    <p>
      Export your <a href="https://cloud.digitalocean.com/settings/api/tokens">DigitalOcean token</a>
      and run the provisioning script to create your platform:
    </p>

    <pre class="p-3 my-4 text-console bg-console border border-console rounded"><code><%= render "console_digitalocean_provisioning" %></code></pre>
  <% end %>

  <hr class="my-4">

  <p>What this script does is install the <a href="https://rubygems.org/gems/provisioning">provisioning gem</a>, download this <%= link_to "manifest file", manifest_path(manifest, format: :json) %>, look for your SSH public key, and run it:</p>

  <pre class="p-3 my-4 text-console bg-console border border-console rounded"><code><%= render "console_manual_provisioning" %></code></pre>

  <hr class="my-4">

  <p>This provisioning manifest will be automatically deleted in less than 24 hours.</p>

  <div class="text-center">
    <%= link_to "Delete now", manifest, data: { confirm: "Are you sure?" }, method: :delete, class: "btn btn-lg btn-outline-danger", role: "button" %>
  </div>
</div>

<%= link_to "&laquo; back".html_safe, root_path, class: "text-muted float-left" %>

app/views/manifests/show.sh.erb
#!/bin/bash

set -eo pipefail

temp=$(mktemp /tmp/provisioning-manifest-<%= manifest.uuid %>.XXXXXXXX)

rmtemp() {
  rm "$temp"
}

main() {
  if ! hash provision 2> /dev/null; then
    gem install provisioning
  fi
  curl -s "<%= manifest_url(format: :json) %>" > "$temp"
  export SSH_PUBLIC_KEY="$(cat ~/.ssh/id_rsa.pub)"
  provision "$temp"
}

trap rmtemp EXIT

main

app/views/welcome/_console_example.html.erb
$ rails new example -d postgresql
$ cd example
$ git add . && git commit # ready to deploy?
$ firefox https://provisioning.sh # fill form, copy link
$ export DIGITALOCEAN_TOKEN=xxxxxxx
$ curl -sSL "https://provisioning.sh?uuid=xxxxxxx" | bash
$ git push dokku master # deployed :)

app/views/welcome/index.html.erb
<div class="content p-4 rounded">
  <h1 class="display-4">Provisioning.sh</h1>
  <p class="lead">A script to setup your own platform as a service</p>

  <hr class="my-4">

  <pre class="p-3 my-4 text-console bg-console border border-console rounded"><code><%= render "console_example" %></code></pre>

  <hr class="my-4">

  <%= form_with model: manifest, local: true, id: "provisioning" do |form| %>
    <div class="form-group row">
      <label for="domain" class="col-sm-2 col-form-label">Domain</label>
      <div class="col-sm-10">
        <input id="domain" name="manifest[app][domains]" type="text" class="form-control" placeholder="example.com" required>
      </div>
    </div>

    <div class="form-group row">
      <label for="app-services" class="col-sm-2 col-form-label">Services</label>
      <div class="col-sm-10">
        <select id="app-services" name="manifest[app][services][]" class="form-control">
          <option value="mongo">Mongo</option>
          <option value="mysql">MySQL</option>
          <option value="postgres" selected>Postgres</option>
        </select>
      </div>
    </div>

    <div class="form-group row">
      <label for="platform" class="col-sm-2 col-form-label">Platform</label>
      <div class="col-sm-10">
        <select id="platform" name="manifest[platform][provider]" class="form-control">
          <option value="dokku" selected>Dokku (1x1GB server)</option>
          <option value="flynn">Flynn (3x2GB cluster)</option>
        </select>
      </div>
    </div>

    <div class="form-group row">
      <label for="cloud" class="col-sm-2 col-form-label">Cloud</label>
      <div class="col-sm-10">
        <select id="cloud" name="manifest[cloud][provider]" class="form-control">
          <option value="aws">Amazon Web Services</option>
          <option value="digitalocean" selected>DigitalOcean</option>
        </select>
      </div>
    </div>

    <div class="text-center mt-5 mb-4">
      <button type="submit" class="btn btn-lg btn-success">Generate</button>
    </div>
  <% end %>
</div>